{% set version = "0.3.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-densityclust
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/densityClust_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/densityClust/densityClust_{{ version }}.tar.gz
  sha256: 54ffec8333a288116c54bd8d500ed3905c993c3b7008157e2047a443d5173846

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - {{ posix }}patch
  host:
    - r-base
    - r-cpp11
    - r-fnn
    - r-ggplot2
    - r-ggrepel
    - r-gridextra
    - r-rcolorbrewer
    - r-rtsne
  run:
    - r-base
    - r-cpp11
    - r-fnn
    - r-ggplot2
    - r-ggrepel
    - r-gridextra
    - r-rcolorbrewer
    - r-rtsne

test:
  commands:
    - $R -e "library('densityClust')"           # [not win]
    - "\"%R%\" -e \"library('densityClust')\""  # [win]

about:
  home: https://github.com/thomasp85/densityClust
  license: GPL-2.0-or-later
  summary: An improved implementation (based on k-nearest neighbors) of the density peak clustering algorithm, originally described by Alex Rodriguez and Alessandro Laio (Science, 2014 vol. 344). It can handle large datasets (> 100, 000 samples) very efficiently. It was initially implemented by Thomas Lin Pedersen, with
    inputs from Sean Hughes and later improved by Xiaojie Qiu to handle large datasets with kNNs.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
