travis:
  secure:
    BINSTAR_TOKEN: dAq0RmIFkxIxT5ge5Tslq415QGgRiidH3JC4m73janP6EUN0ep4EiTaWE8mu6BAglHRRYx65yoSQAIkdZEeQy9fNBvbbflLhxUuOcR5YtzGs99KpawX+J6JAn2gTAvFpGHbjqBnN2e159TnlBO6nE/fZEMMIFWGWPCXKsy0qV4iyWv+UCpfELAFUTJyE/6ZffpKBVwOrlsMw/Y5odHo7uDrx8KaE3SoLl/Corv4lrs37dPJS8wr7f4V0NCybhWQDyI0sgySh6eeRCkB8eNF01kVb/fkWySCkvR3xkbZmz5yJZG84pFy8iAOLS7BQwfXTltIFWkrvGT0YaKcK8toisp/amw3L+MNze4B06Kd4ieQreEk9mqcZCJAdap2UaxrXQHEsNaXHo5wOsRRWf4bABu8pZGIcgDsrdmBUz7p06lF4yhWNG5ED/QIb7a1f27Ek7kBtRV2WH7sviPR8QXsD5P5Ge6fvgt4/R3SNhdcsjcp8PcXwOaAI9tIlnwOjoYTFtegCIfuR3oybJ+LVIBdEe8UYS4XuatHmi8rLrgrB3ZHiIuW3GWdHLrvw4IvLDCBmMJJPrhJjYKqKLVv4vlicqId1uHiy4uX7nye3MgYNDrlaYgm250hxqfKUgn7f53ebVWglWEUpAhwCxfW5/64M7k/8Oc8AVjuW8ixQBU7qeCU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
