travis:
  secure:
    BINSTAR_TOKEN: NXTu2sMSKkGP/XW3xgUoQqhnzQ33bxc16qmJfpd7wJzFC8ZbfLxEos79CDEmunJDigul7aJcT6JyPQzWdLxUbgFEKYNaBIJLCiUMi4wzvDmUs3tpCNZSIruRkIChdsVoHAOreFFz99/tDub5c+Qhg2YaUAS3MpRrbQzD3ARWktgEkJiVocrWXvze3IxK7U1DWTS5fz0QxTa1CsuYpkm89neXlC6+W7TYFGnPEyOyjfgTHg5pG6py8yKHbADqiITQz1roLQmkRonYv9883bU0kbrdBBBJ0TbtWX1mCfjT9889+qqIxmL7LmFMhGU97NKKi2qIvLqLaCYIaNnNW1vUWLWPJF/2d9XMo0Z96IblzvAqCVXbyRoULSrdDyppVD/ywYI1ubDqjOtHlzQhZmp3QH1vnGhNYu3d3oQOm6zPLaCkXzLOobfpOSrD2n77fbjIZtuQiSK6P1//0y8h0QF6JH+Cu8562Izq4iOZ6QPvqUnbF+axVfxbqP1fZBdnbz/XGnE7xhH+D1B5ALwNw8k+dICnnJ5+r5EWZVHUVSpvNClsanC4cbBAFz1TgNBEYfqK5kMxpSKvQwzA2QzdNIL+8REPMkdkxhZn8fU0rI+IhVou6X2Qzdo/rcHxMFhfsANHQ3dyXakhubpB52Ob2+2pPluv2WXci1BKIN4sxhZPyKs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
